export const STAT_KEYS = [
  'speed',
  'stamina',
  'navigation',
  'agility',
  'instinct',
  'recovery',
  'focus',
  'burst',
  'weatherResistance',
  'experience',
];

export const TRAIT_MODIFIERS = {
  aero_feathers: { speed: 4, agility: 2, stamina: -1 },
  courier_bag: { stamina: -2, focus: 4, navigation: 2 },
  mechanical_wing: { burst: 7, speed: 3, recovery: -4 },
  stormproof: { weatherResistance: 8, stamina: 2, speed: -2 },
  night_vision: { navigation: 6, focus: 4 },
  veteran_band: { experience: 7, instinct: 2 },
  lightweight_harness: { speed: 3, stamina: 3, focus: -1 },
  rooftop_scout: { agility: 5, navigation: 4 },
  lucky_charm: { instinct: 6 },
  reinforced_pack: { weatherResistance: 3, recovery: 4, speed: -2 },
};

export const COURSE_PRESETS = {
  citySprint: {
    type: 'citySprint',
    name: 'Rooftop Rush',
    distanceKm: 5.5,
    routeComplexity: 82,
    urbanDensity: 94,
    windKph: 14,
    windAngleDeg: 210,
    temperatureC: 23,
    rainMmPh: 0,
    visibilityKm: 18,
    turbulence: 45,
    predatorRisk: 22,
    interference: 68,
    altitudeM: 120,
    timeOfDay: 'day',
    checkpoints: 8,
  },
  longHaul: {
    type: 'longHaul',
    name: 'Long Haul Relay',
    distanceKm: 72,
    routeComplexity: 38,
    urbanDensity: 24,
    windKph: 24,
    windAngleDeg: 160,
    temperatureC: 28,
    rainMmPh: 0.5,
    visibilityKm: 34,
    turbulence: 30,
    predatorRisk: 28,
    interference: 15,
    altitudeM: 420,
    timeOfDay: 'day',
    checkpoints: 12,
  },
  stormRun: {
    type: 'stormRun',
    name: 'Stormfront Dash',
    distanceKm: 24,
    routeComplexity: 58,
    urbanDensity: 52,
    windKph: 48,
    windAngleDeg: 275,
    temperatureC: 17,
    rainMmPh: 9,
    visibilityKm: 4,
    turbulence: 86,
    predatorRisk: 12,
    interference: 35,
    altitudeM: 300,
    timeOfDay: 'day',
    checkpoints: 10,
  },
  nightFlight: {
    type: 'nightFlight',
    name: 'Midnight Courier',
    distanceKm: 18,
    routeComplexity: 72,
    urbanDensity: 76,
    windKph: 10,
    windAngleDeg: 20,
    temperatureC: 14,
    rainMmPh: 0,
    visibilityKm: 3.5,
    turbulence: 25,
    predatorRisk: 34,
    interference: 48,
    altitudeM: 180,
    timeOfDay: 'night',
    checkpoints: 10,
  },
  mountainCrossing: {
    type: 'mountainCrossing',
    name: 'High Country Crossing',
    distanceKm: 46,
    routeComplexity: 63,
    urbanDensity: 8,
    windKph: 34,
    windAngleDeg: 110,
    temperatureC: 7,
    rainMmPh: 1.2,
    visibilityKm: 15,
    turbulence: 72,
    predatorRisk: 42,
    interference: 4,
    altitudeM: 1250,
    timeOfDay: 'day',
    checkpoints: 12,
  },
};
